export const UPDATE_PRODUCT_LIST = "DEVICE_UPDATE_PRODUCT_LIST"; // 产品列表
export const UPDATE_DEVICE_STAT = "UPDATE_DEVICE_STAT"; // 设备统计
export const UPDATE_DEVICE_LIST = "UPDATE_DEVICE_LIST"; // 设备列表
export const UPDATE_DEVICE_LABEL = "UPDATE_DEVICE_LABEL"; // 设备标签列表
export const UPDATE_DEVICE_LABELBASE = "UPDATE_DEVICE_LABELBASE"; // 标签库列表
export const UPDATE_DEFAULT_DEVICE_LABEL = "UPDATE_DEFAULT_DEVICE_LABEL"; // 默认设备标签
export const UPDATE_DEVICE_COUNT_STATU = "UPDATE_DEVICE_COUNT_STATU"; //设备统计 接口是否更新完成