
const OTAACTION = 'OTA_ACTIONTYPE_'
export const GETPROLIST = OTAACTION+'GETPROLIST';
export const GETVERLI = OTAACTION+'GETVERLIST';
export const EXTVERLI = OTAACTION+'GETEXTVERLI';
export const DEVGROUPLIST = OTAACTION+'GETDEVGROUPLI';
export const FIRMWAREDETAIL = OTAACTION+'FIRMWAREDETAIL';

